### ISSUE TITLE
博主，你好！出现error：“SEACAVE::String &SEACAVE::Util::ensureUnifySlash(SEACAVE::String &)”: 无法将参数 1 从“SEACAVE::String”转换为“SEACAVE::String &”

### ISSUE THREAD

**Issue by xiaojin-code** [SoulBasic/J3DReconstruction#2]
博主，你好！出现error：“SEACAVE::String &SEACAVE::Util::ensureUnifySlash(SEACAVE::String &)”: 无法将参数 1 从“SEACAVE::String”转换为“SEACAVE::String &”无法编译J3Dgui.exe,其他编译成功，可否告知解决方法，感激不尽

**Comment by SoulBasic** [comment]
这里是因为msvc2017编译器升级，使隐式转换的条件更苛刻导致的问题，尝试一下拉一下J3DReconstruction的最新代码，并将 openMVS\src\libs\Common\Util.h的280行改成static String& ensureUnifySlash(String path)试试呢

**Comment by YT-Chow** [comment]
改成static String& ensureUnifySlash(String path)这个 会导致异常出现 Debug Assertion Failed
