### ISSUE TITLE
我用qt 5.15.2 MSVC，根据release的2.3版本和依赖库打包，可以运行，但GUI的指令发不到引擎上

### ISSUE THREAD

**Issue by shiwangyan** [SoulBasic/J3DReconstruction#3]
我没装5.14.2，我觉得15跟14差距应该不大，所以就用15了，难道是因为qt版本不对导致的吗？

**Comment by SoulBasic** [comment]
可能是没有用管理员身份打开，因为这个指令传递是靠命令文件读写实现的，默认写到了C盘，不用管理员身份打开程序可能会没有权限导致写失败
